#ifndef SYSTEM_TRAY_PROTOCOL_H
#define SYSTEM_TRAY_PROTOCOL_H

#define NET_SYSTEM_TRAY_S "NET_SYSTEM_TRAY_S"
#define NET_SYSTEM_TRAY_OPCODE "NET_SYSTEM_TRAY_OPCODE"

#define SYSTEM_TRAY_REQUEST_DOCK 0
#define SYSTEM_TRAY_BEGIN_MESSAGE 1
#define SYSTEM_TRAY_CANCEL_MESSAGE 2

#endif
